#db __init__.py
from ..exceptions.Exceptions import UserExistsException