#exceptions __init__.py